# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-01-04 02:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SnakeId',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('thumb', models.CharField(blank=True, max_length=80, null=True)),
                ('species', models.CharField(blank=True, max_length=50, null=True)),
                ('img_file', models.CharField(blank=True, max_length=80, null=True)),
                ('r', models.IntegerField(blank=True, null=True)),
                ('b', models.IntegerField(blank=True, null=True)),
                ('g', models.IntegerField(blank=True, null=True)),
                ('h', models.FloatField(blank=True, null=True)),
                ('s', models.FloatField(blank=True, null=True)),
                ('v', models.FloatField(blank=True, null=True)),
                ('html', models.CharField(blank=True, max_length=8, null=True)),
                ('source', models.CharField(blank=True, max_length=100, null=True)),
            ],
            options={
                'db_table': 'snake_id',
                'managed': True,
            },
        ),
    ]
